Progress bar
ilastik/hytra pull request #22
Opened 2017-03-16 12:37 UTC by ilastikdev

if gui is present it displays a progress dialog box
if not it will display progress on command line

2017-03-16 13:08 UTC, chaubold commented
Right now your `exportStep` and `exportProgress` default to nothing, and that clutters the code with `if not self.exportStep==None` (which should have been `if self.exportStep is not None` btw.).

For one, this should default to the command line progress bar as before. And I'm not really happy with the way the code looks. Perhaps it is because the variable names are a little confusing.

Do you know the [visitor design pattern](https://www.tutorialspoint.com/design_pattern/visitor_pattern.htm)? To make this nice from a software design perspective, you should call the `exportStep` things something like a `progressVisitor`. Then create a base class for the visitor that defines which methods it provides, make a default implementation (e.g. `CommandLineProgressVisitor`) to which this is set by default, and in the hypotheses graph provide a method to set a user defined visitor (e.g. `HypothesesGraph.setProgressVisitor`). And lastly on the ilastik side you can derive the `IlastikProgressVisitor` and pass that in as needed.

And to get rid of all the `is not None` checks throughout the code we should not allow the visitor to be set to `None` within `HypothesesGraph.setProgressVisitor`.

2017-03-22 14:23 UTC, ilastikdev commented
visitor functions changed to visitor class
DefaultProgressVisitor and CommandLineProgressVisitor are defined in hytra
one can also setProgressVisitor from frontend

2017-03-24 06:57 UTC, chaubold requested changes

2017-03-24 06:57 UTC, chaubold commented on hytra/core/jsongraph.py
> +                 progressVisitor=ProgressVisitor()):
This should be `DefaultProgressVisitor()`.

2017-03-24 06:57 UTC, chaubold commented on hytra/util/progressbar.py
> +    def setProgressVisitor(self,progressVisitor):
I don't get the `ProgressVisitor`. It subclasses `DefaultProgressVisitor` which provides only empty methods, so setting `self.progressVisitor` here doesn't have any consequences, same as setting all the other members. I think that class should be removed. Also, it is not used from the ilastik side but there you did what one would expect -- you derived a special visitor for the Gui progress bar.

2017-03-24 08:58 UTC, ilastikdev commented
removed... just a left over from the time I planed to use setProgressVisitor ... but that is actually not needed

2017-03-24 09:03 UTC, chaubold approved these changes

2017-03-24 09:04 UTC, merged